version: "3.7"

services:
    # image project
    laravel_repository:
        container_name: laracel_repository_laravel-9
        build:
            context: .
            dockerfile: Dockerfile
        image: especializati/laravel9-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - repository
    
    # nginx
    nginx:
        container_name: laracel_repository_nginx
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8010:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - repository

    # db mysql
    mysql:
        container_name: laracel_repository_mysql
        image: mysql:5.7.22
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - "3326:3306"
        networks: 
            - repository

    # queue
    queue:
        container_name: laracel_repository_queue
        image: especializati/laravel9-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./:/var/www
        depends_on: 
            - redis
            - laravel_repository
        networks: 
            - repository

    # redis
    redis:
        container_name: laracel_repository_redis
        image: redis:latest
        networks: 
            - repository

networks: 
    repository:
        driver: bridge